### ISSUE TITLE
Readme.md Update Needed!

### ISSUE THREAD

**Issue by Raeskaa** [prince776/c2ladders#1]
Hey, 
I was going through the repo and I wasn't able to figure out how to run the site locally in my system ( I wanted to contribute to the frontend part). The readme must be updated and at least "How to deploy the app locally" must be added for contributors to start contributing. 
PS: The website is really awesome 🔥

**Comment by prince776** [comment]
I need to figure out how contributors will access database, once I do, I'll update readme

**Comment by prince776** [comment]
Readme update, please check
