### ISSUE TITLE
C2Ladders site is down

### ISSUE THREAD

**Issue by sharuf-baig** [prince776/c2ladders#5]
The website is down and showing the error as mentioned below 

![image](https://user-images.githubusercontent.com/49720926/172054036-526573ab-4ea2-4223-bdc9-430f3548e42c.png)

**Comment by prince776** [comment]
No idea why this is happening, will update once fixed

**Comment by prince776** [comment]
Should be working now, idk why but all my db users expired suddenly, Had to re add that.

**Comment by sharuf-baig** [comment]
Cool, now it's working fine!!!
